Add visitor pattern sample
Kostyanoid/GOF-Patterns-Samples pull request #3
Opened 2019-11-21 15:17 UTC by Kostyanoid

2019-11-21 19:04 UTC, AleksandrRadchenko requested changes

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +        Shape circle = new Circle(1, 1,1);
Space after ","

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +        shapes.forEach(shape -> logger.info(shape.toString()));
`.toString()` will be called automatically

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +
Extra line. Do we really need it?

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Point.java
> +public class Point {
Why Point is not a Shape? It can even be implemented as a Circle with zero radius.

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Circle.java
> +    }
Why not to use Lombok for all this boilerplate?

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Rectangle.java
> +    public double getArea() {
Where is `@Override`

2019-11-21 19:04 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Rectangle.java
> +    public double getPerimeter() {
Same here

2019-11-21 20:00 UTC, AleksandrRadchenko requested changes
I suppose that it's not correct Visitor Pattern implementation. The essence of the Pattern is the possibility to add behavior to the class hierarchy without modifying hierarchy source sode. That can't be achieved.

2019-11-21 20:00 UTC, AleksandrRadchenko commented on visitor/src/main/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Do we really need separate logging configuration for each Pattern Sample?

2019-11-21 20:00 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/visitors/AbstractShapeVisitor.java
> +        return Math.sqrt(xLength*xLength + yLength*yLength);
Inconsistent formatting: no spaces around operands.

2019-11-21 20:00 UTC, AleksandrRadchenko commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/visitors/AbstractShapeVisitor.java
> +    protected static final double PI = Math.PI;
Is PI constant supposed to be overridden? :)

2019-11-22 10:08 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +        shapes.forEach(shape -> logger.info(shape.toString()));
и чо?

2019-11-22 10:08 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +        Shape circle = new Circle(1, 1,1);
и чо?

2019-11-22 10:09 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/VisitorSample.java
> +
really?!! very essential comment!

2019-11-22 10:10 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Point.java
> +public class Point {
Point is not a Shape.

2019-11-22 10:13 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Circle.java
> +    }
I thought about Lombok but decided not use it because, in my opinion, it makes readability worse

2019-11-22 10:13 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Rectangle.java
> +    public double getArea() {
Actually, It as not necessary when you implement interface methods

2019-11-22 10:14 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/model/Rectangle.java
> +    public double getPerimeter() {
Same here

2019-11-22 10:15 UTC, Kostyanoid commented on visitor/src/main/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Yes, if you look more carefully there are some differences.

2019-11-22 10:32 UTC, Kostyanoid reviewed
It's quite proper Visitor implementation since we have one separate class to do work for various classes in hierarchy. If you have some doubts you can ask uncle Bob (on page 124 his "Clean code" book, Russian edition)

2019-11-22 10:32 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/visitors/AbstractShapeVisitor.java
> +        return Math.sqrt(xLength*xLength + yLength*yLength);
See Robert C. Martin horizontal alignment with operands conception

2019-11-22 10:32 UTC, Kostyanoid commented on visitor/src/main/java/rk/samples/gofpatterns/visitor/visitors/AbstractShapeVisitor.java
> +    protected static final double PI = Math.PI;
I think it looks quite appropriate here

2019-11-26 08:17 UTC, merged